"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import { ViewProvider } from "../../public/context/View.ctx";
import { CartProvider } from "../../public/context/Cart.ctx";
import { UserProvider } from "../../public/context/Session.ctx";
import { LoadingProvider } from "../../public/context/Loading.ctx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Client",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/icon-192x192.png",  // Path to your PWA icon
    apple: "/icons/icon-512x512.png",
  },
  manifest: "/manifest.json", // Ensure this file is in the `public` folder
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Register PWA Service Worker
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", () => {
        navigator.serviceWorker
          .register("/service-worker.js")
          .then((reg) => console.log("Service Worker registered: ", reg))
          .catch((err) => console.log("Service Worker registration failed: ", err));
      });
    }
  }, []);

  return (
    <LoadingProvider>
      <UserProvider>
        <CartProvider>
          <ViewProvider>
            <html lang="en">
              <head>
                <link rel="manifest" href="/manifest.json" />
                <meta name="theme-color" content="#000000" />
              </head>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                {children}
              </body>
            </html>
          </ViewProvider>
        </CartProvider>
      </UserProvider>
    </LoadingProvider>
  );
}
